version: "3.9"

services:
    app1:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - postgres
        volumes:
            - .:/var/www/html:delegated
            - /var/www/html/vendor
        ports:
            - "9001:9000"
        environment:
            - APP_NAME=App1

        # networks:
        #   - app-network
    # app2:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     restart: unless-stopped
    #     depends_on:
    #         - postgres
    #     volumes:
    #         - .:/var/www/html:delegated
    #         - /var/www/html/vendor
    #     ports:
    #         - "9002:9000"

    #     environment:
    #         - APP_NAME=App2

    # networks:
    #   - app-network
    # app3:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     restart: unless-stopped
    #     depends_on:
    #         - postgres
    #     volumes:
    #         - .:/var/www/html:delegated
    #         - /var/www/html/vendor
    #     ports:
    #         - "9003:9000"
    #     environment:
    #         - APP_NAME=App3

    # networks:
    #   - app-network

    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_USER: streamledger
            POSTGRES_PASSWORD: streamledger
            POSTGRES_DB: streamledger
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        # networks:
        #   - app-network

    nginx:
        image: nginx:stable-alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - /var/www/html/vendor
        depends_on:
            - app
            - postgres

    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
        entrypoint: ["php", "/var/www/html/artisan"]
volumes:
    pgdata:
# networks:
#   app-network:
#     driver: bridge
